# Generated by Django 3.0.8 on 2020-08-27 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abonnes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
